# Generated by Django 4.1 on 2022-09-04 16:28

import birthday.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Zip',
            field=models.CharField(default='', help_text='Zip Code', max_length=5, validators=[django.core.validators.RegexValidator('\\d\\d\\d\\d\\d')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=birthday.fields.BirthdayField(help_text='YY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(choices=[('D1', 'DEPARTMENT1'), ('D2', 'DEPARTMENT2'), ('D3', 'DEPARTMENT3'), ('D4', 'DEPARTMENT4'), ('D5', 'DEPARTMENT5'), ('D6', 'DEPARTMENT6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Post',
            field=models.CharField(max_length=10),
        ),
    ]
