# Generated by Django 4.1 on 2022-09-04 16:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_zip_alter_employee_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(default='AL', max_length=2),
        ),
    ]
