# Generated by Django 4.1 on 2022-09-04 17:03

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='City',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='employee',
            name='State',
            field=models.CharField(default='Leave_count', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(default='IN', max_length=2),
        ),
    ]
